@startuml diagramme de séquence

skinparam responseMessageBelowArrow true

participant Jeu
participant PremiereNormale
participant "Borne/Frontière" as Tuile
participant PiocheNormale
participant Main
actor Agent

activate Jeu #LightBlue
Jeu -> Jeu: commencerJeu()

loop #Azure une partie du jeu

==Initialisation==

    Jeu -> PremiereNormale: jouerPartie(Edition, Variante)
    activate PremiereNormale #LightGreen
    activate Tuile #LightGreen
    PremiereNormale -> PiocheNormale: initierPioche()
    activate PiocheNormale #LightGreen
    Jeu -> Jeu: determinerOrdre()
    Jeu -> PremiereNormale: commencer(Ordre)
    PremiereNormale -> Main: initierMain()
    activate Main #LightGreen
    PremiereNormale -> Agent: initierAgent()
    activate Agent #LightGreen

==Déroulement==

    loop #Ivory un tour dans une partie
        Jeu -> PremiereNormale: testerFin()
        Jeu -> PremiereNormale: jouerTour()
        group #Cornsilk jouer
            PremiereNormale -> Agent: jouer(Frontière)
            activate Agent #MediumSeaGreen
            Agent -> Agent: choisirCarteAJouer()
            Agent -> Agent: choisirBornesARevendiquer()
            ' Agent -> Tuile: verifRevendicable(Borne, Agent)
            Agent -> PremiereNormale: Mouvement
            deactivate Agent
            PremiereNormale -> Agent: jouerCarte(Frontière, Carte, Borne, Agent)
            PremiereNormale -> Agent: revendiquerBorne(Frontière, Borne, Agent)
            Agent -> Tuile: revendiquerBorne(Frontière, Borne, Agent)
        end

        group #Cornsilk piocher
            PremiereNormale -> PiocheNormale: piocher(Carte)
            PremiereNormale -> Agent: piocher(Carte)
        end

        PremiereNormale -> PremiereNormale: agentSuivant()
    end

==Terminaison==

    Jeu -> PremiereNormale: terminer()
    deactivate PiocheNormale
    deactivate Main
    deactivate Agent
    deactivate PremiereNormale
    deactivate Tuile
    Jeu -> Jeu: traiterResultats()

end

Jeu -> Jeu: finirJeu()
deactivate Jeu

note across #Ivory
    Le jeu est composé de plusieurs parties qui sont jouées à la suite.
    Une partie est composée de plusieurs tours qui sont joués à la suite.

    Une partie se termine quand un des joueurs a revendiqué suffisamment de bornes.

    On représente ici surtout les interactions entre les différents objets,
    les méthodes bas niveau ne sont pas représentées.
end note

@enduml
